[studybubble]
name = LearnTerraform
mode = single-file
default_topic = terraform_1000_foot_view

topics_dir = topics
layouts_dir = layouts
outputs_dir = outputs
assets_dir = assets
downloads_dir = D:/Users/shareuser/Downloads

[engine]
path = ../../../Study_bubbles

[projects]
# Optional future map-of-maps references.
# aws = ../AWS
# powerbi = ../../PowerBI
# opentelemetry = ../../OpenTelemetry