services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${_POSTGRES_USER}
      POSTGRES_PASSWORD: ${_POSTGRES_PASSWORD}
      POSTGRES_DB: ${_POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${_POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  redis:
    image: redis:7.2-bookworm
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres-db-volume: