"""
01_run_build_seed_docs.py — dbt build, docs generate, and artifacts.

Teaches:
  - dbt run vs dbt build vs dbt test (and when to use each)
  - dbt docs generate: what it produces (manifest.json, catalog.json, index.html)
  - manifest.json: the machine-readable project graph (used by CI/CD tools)
  - run_results.json: per-node execution results (used by observability tools)
  - How to parse manifest.json to extract lineage programmatically
  - The difference between dbt artifacts and why each matters

Key concept:
  dbt build = seed + run + test + snapshot in DAG order.
  It's the "full pipeline" command — use this in CI/CD instead of run + test separately.

  manifest.json is the "contract" artifact:
    - Every node (model, test, seed, snapshot) with its SQL, config, dependencies
    - Used by dbt Cloud, Lightdash, elementary, re_data, etc.
    - Key for CI/CD: state comparison (state:modified)

Run:
    python 05_operations_and_deploy/01_run_build_seed_docs.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from _dbt_lane_connect import (
    DBT_PROJECT_DIR,
    run_dbt,
    write_profiles_yml,
)


def explain_commands() -> None:
    print("""
--- dbt Command Comparison ---

  dbt seed       → Load CSV files into DB as tables
  dbt run        → Execute model SQL (CREATE VIEW/TABLE/...)
  dbt test       → Run all tests (generic + singular)
  dbt snapshot   → Run SCD Type 2 snapshots
  dbt docs generate → Build manifest.json + catalog.json + index.html
  dbt docs serve    → Serve docs in browser (localhost:8080)

  dbt build      → seed + run + test + snapshot in DAG order
                   Each node: run first, then test before moving downstream
                   SAFEST: if a model's tests fail, downstream won't run

  CI/CD best practice:
    dbt build --select state:modified+  (only changed models + downstream)
    → Saves cost: only rebuild what changed

--- Artifact files in target/ ---

  manifest.json   → Full project graph: nodes, sources, tests, macros, configs
                    Generated by: compile, run, test, build, docs generate
                    Key fields: nodes (model SQL + DAG), sources, macros

  run_results.json → Per-execution results: status, timing, row_count
                     Re-written on each command run
                     Used by observability tools (elementary, re_data, Montecarlo)

  catalog.json    → DB introspection: column names, types, row counts
                    Only generated by: dbt docs generate
                    Used by the docs UI for column-level lineage

  sources.json    → Source freshness results (from dbt source freshness)
    """)


def parse_manifest() -> dict:
    """Load and return manifest.json from target/."""
    manifest_path = DBT_PROJECT_DIR / "target" / "manifest.json"
    if not manifest_path.exists():
        return {}
    try:
        return json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def show_manifest_summary(manifest: dict) -> None:
    """Print top-level stats from manifest.json."""
    if not manifest:
        print("  (manifest.json not found — run dbt build first)")
        return

    nodes = manifest.get("nodes", {})
    sources = manifest.get("sources", {})
    macros = manifest.get("macros", {})

    # Count by resource type
    from collections import Counter
    type_counts = Counter(v.get("resource_type", "?") for v in nodes.values())

    print(f"\n  manifest.json — top-level stats:")
    print(f"    dbt_schema_version : {manifest.get('metadata', {}).get('dbt_schema_version', '?')}")
    print(f"    dbt_version        : {manifest.get('metadata', {}).get('dbt_version', '?')}")
    print(f"    Total nodes        : {len(nodes)}")
    for rtype, count in sorted(type_counts.items()):
        print(f"      {rtype:15s}: {count}")
    print(f"    Sources            : {len(sources)}")
    print(f"    Macros             : {len(macros)}")

    # Show DAG for one model
    target_node = None
    for uid, node in nodes.items():
        if node.get("name") == "fct_orders" and node.get("resource_type") == "model":
            target_node = node
            break
    if target_node:
        deps = target_node.get("depends_on", {}).get("nodes", [])
        print(f"\n  fct_orders DAG dependencies (from manifest):")
        for dep in deps:
            print(f"    → {dep}")


def show_run_results_summary() -> None:
    """Parse run_results.json and show per-node status."""
    results_path = DBT_PROJECT_DIR / "target" / "run_results.json"
    if not results_path.exists():
        print("  (run_results.json not found)")
        return
    try:
        data = json.loads(results_path.read_text(encoding="utf-8"))
        results = data.get("results", [])
        print(f"\n  run_results.json — {len(results)} nodes:")
        for r in results[:20]:
            uid = r.get("unique_id", "?").split(".")[-1][:40]
            status = r.get("status", "?")
            timing = r.get("execution_time", 0)
            rows = r.get("adapter_response", {}).get("rows_affected", "?")
            print(f"    {status:6} | {timing:5.2f}s | rows={rows!s:6} | {uid}")
        if len(results) > 20:
            print(f"    ... ({len(results) - 20} more)")
    except Exception as e:
        print(f"  (Could not parse run_results.json: {e})")


def main() -> int:
    print("=" * 60)
    print("  Operations — dbt build, docs, and artifacts")
    print("=" * 60)

    explain_commands()

    write_profiles_yml()

    # Step 1: Run dbt build (full pipeline)
    print("\n[Step 1] Running `dbt build`...")
    print("  (This runs: seed → run → test for each node in DAG order)\n")
    rc, stdout, stderr = run_dbt(["build"], timeout=300)
    output = (stdout + "\n" + stderr).strip()
    for line in output.splitlines()[-25:]:
        print(f"  {line}")

    if rc != 0:
        print(f"\n  [NOTE] dbt build returned rc={rc}")
        print("  Some tests may fail (intentional seed data: duplicate emails, 0-amount payments)")
        print("  This is expected — the build itself ran, teaching the flow.")

    # Step 2: Generate docs
    print("\n[Step 2] Running `dbt docs generate`...")
    rc_docs, stdout_docs, stderr_docs = run_dbt(["docs", "generate"], timeout=180)
    for line in (stdout_docs + "\n" + stderr_docs).strip().splitlines()[-8:]:
        print(f"  {line}")

    # Step 3: Parse manifest
    print("\n[Step 3] Parsing manifest.json...")
    manifest = parse_manifest()
    show_manifest_summary(manifest)

    # Step 4: Parse run_results
    print("\n[Step 4] Parsing run_results.json...")
    show_run_results_summary()

    # Step 5: Show artifact files
    target_dir = DBT_PROJECT_DIR / "target"
    print(f"\n[Step 5] Artifact files in {target_dir}:")
    artifact_files = ["manifest.json", "run_results.json", "catalog.json",
                      "sources.json", "index.html"]
    for f in artifact_files:
        p = target_dir / f
        if p.exists():
            size_kb = p.stat().st_size / 1024
            print(f"  ✓ {f:25s} ({size_kb:.1f} KB)")
        else:
            print(f"  · {f:25s} (not generated yet)")

    print()
    print("KEY TAKEAWAYS:")
    print("  1. dbt build = seed + run + test in DAG order; safest CI/CD command")
    print("  2. manifest.json = the graph; used by every dbt observability tool")
    print("  3. run_results.json = execution log; parse for alerting / dashboards")
    print("  4. catalog.json = DB column metadata; generated only by docs generate")
    print("  5. In CI/CD: upload manifest.json as artifact for state:modified diff")
    print("  6. dbt docs serve → localhost:8080 for interactive lineage graph")
    print()
    print("PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
