output "change_summary" {
  description = "Shows the local-safe change review metadata."
  value       = local.change_summary
}

output "safety_message" {
  description = "Shows the safety message generated by the lab."
  value       = local.safety_message
}

output "safety_review_demo_output" {
  description = "Shows local-safe data flowing through the safety review demo."
  value       = terraform_data.safety_review_demo.output
}
